Category:
  type: entity
  table: categories
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string

  manyToMany:
    groups:
      targetEntity: Image
      joinTable:
        name: categories_images
        joinColumns:
          categories_id:
            referencedColumnName: id
        inverseJoinColumns:
          images_id:
            referencedColumnName: id